os: linux
dist: bionic

language: csharp

services:
  - docker

before_install:
  # Decrypt the git_deploy_key.enc key into /tmp/git_deploy_key
  - openssl aes-256-cbc -K $encrypted_f1dafbfceca1_key -iv $encrypted_f1dafbfceca1_iv -in id_rsa.pub.enc -out DevOpsMinitwit/ -d
  # Make sure only the current user can read the private key
  - chmod 600 /tmp/git_deploy_key
  # Create a script to return the passphrase environment variable to ssh-add
  - echo 'echo ${SSH_PASSPHRASE}' > /tmp/askpass && chmod +x /tmp/askpass
  # Start the authentication agent
  - eval "$(ssh-agent -s)"
  # Add the key to the authentication agent
  - DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add /tmp/git_deploy_key </dev/null

install:
  - docker --version  # document the version travis is using

stages:
  - docker_build
  - deploy


jobs:
  include:
    - stage: docker_build
      name: "Build and push docker"
      script:
        - docker-compose build
        - docker-compose push
    
    - stage: deploy
      name: "Deploy to server"
      script: |
        - ssh root@188.166.123.44
        - docker-compose -f DevOpsMinitwit/docker-compose.yml pull
        - docker-compose -f DevOpsMinitwit/docker-compose.yml up -d