version: "3"
services:
    webapi:
        build:
            context: .
            dockerfile: Dockerfile-api
        image: jemol/minitwit_api:latest
        ports: 
        - "5001:80"

    blazor_web_app:
        build:
            context: .
            dockerfile: Dockerfile-blazor
        image: jemol/minitwit_blazor:latest
        ports: 
        - "8001:80"

