version: "3"
services:
        api:
                build:
                        context: .
                        dockerfile: Dockerfile-api
        blazor:
                build:
                        context: .
                        dockerfile: Dockerfile-blazor
