version: "3"

services:
    webapi:
        build:
            context: .
            dockerfile: Dockerfile-api
        image: jemol/minitwit_api:latest
        ports: 
        - "5001:80"
        depends_on:
        - prometheus
        - grafana

    blazor_web_app:
        build:
            context: .
            dockerfile: Dockerfile-blazor
        image: jemol/minitwit_blazor:latest
        ports: 
        - "8001:80"

    prometheus:
        image: prom/prometheus
        container_name: prometheus
        volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
        - "9090:9090"

    grafana:
        image: grafana/grafana:4.5.2
        volumes:
        - ./docker_data:/var/lib/grafana
        ports:
        - "3000:3000"
