name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

env:
  # TODO: Change variable to your image's name.
  COMPOSE_FILE: Docker-compose.yml

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
      
  deploy:
    #deploy after pushing the images to docker hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: shimataro/ssh-key-action@v2.2.0
        with:
          key: ${{ secrets.SSH_KEY_P }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
        
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
      - run:
          | 
          doctl compute droplet list
          doctl compute ssh ${{ secrets.DROPLET_ID }} --ssh-key-path ~/.ssh
