name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

env:
  # TODO: Change variable to your image's name.
  COMPOSE_FILE: Docker-compose.yml

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
      
  deploy:
    #deploy after pushing the images to docker hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Create SSH key
        run: |
          mkdir ~/.ssh/
          echo "${{secrets.SSH_KEY_P}}" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          eval `ssh-agent`
          ssh-add ~/.ssh/id_rsa
          echo "${{secrets.SSH_KNOWN_HOSTS}}" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_KEY_P}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: $GITHUB_WORKSPACE/../private.key
      - name: deploy images
        run: |
          ls
          cd $GITHUB_WORKSPACE
          ls
          ssh -i $SSH_KEY_PATH ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}
