name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - 'feature/61/actionsSetup'

env:
  # TODO: Change variable to your image's name.
  COMPOSE_FILE: docker-compose.yml

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: test step 1
        run: |
          echo jeg tester ting :D
          
  push:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - uses: actions/checkout@v2
      - name: docker-compose push
        run: |
          docker-compose -f $COMPOSE_FILE build
          docker-compose -f $COMPOSE_FILE push
      
  deploy:
    runs-on: ubuntu-latest
    needs: push

    steps:
      - uses: actions/checkout@v2
      
      - name: Create SSH key
        run: |
          mkdir ~/.ssh/
          echo "${{secrets.SSH_KEY_P}}" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          eval `ssh-agent`
          ssh-add ~/.ssh/id_rsa
        shell: bash
      - name: run deploy script on droplet
        run: |
          ssh -o "StrictHostKeyChecking no" ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} < deploy.sh
