name: Run Infer# Analysis

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100'

    - name: Build with dotnet
      run: dotnet build MiniTwitAPI/MiniTwitAPI.sln
    
    - name: Run Infer#
      id: runinfersharp
      uses: microsoft/infersharpaction@v1.0
      with:
        binary-path: 'MiniTwitAPI'
    - name: Infer# analysis results
      run: echo "${{ steps.runinfersharp.outputs.results }}"
